apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-reverseproxy
  template:
    metadata:
      labels:
        app: udagram-reverseproxy
    spec:
      containers:
        - name: udagram-reverseproxy
          image: juniornguyen/udagram-reverseproxy
          ports:
            - containerPort: 80