apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend
  labels:
    run: udagram-frontend
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: udagram-frontend