apiVersion: v1
kind: Service
metadata:
  name: udagram-api-feed
  labels:
    run: udagram-api-feed
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: udagram-api-feed