apiVersion: v1
kind: ConfigMap
metadata:
  name: udagram-config-map
data:
  POSTGRES_USERNAME: "smee"
  POSTGRES_PASSWORD: "Unbreakable"
  POSTGRES_HOST: "postgres.cccvejvzxfqp.us-east-1.rds.amazonaws.com"
  POSTGRES_DB: "postgres"
  AWS_BUCKET: 'proj-3-udacity'
  AWS_REGION: "us-east-1"
  AWS_PROFILE: "udacity3"
  JWT_SECRET: "testing"